import Tetris from "@/components/tetris";
import styled from "@emotion/styled";
import type { NextPage } from "next";
import Head from "next/head";

const Container = styled("div")`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`;

const Main = styled("main")`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  height: 100vh;
`;

const Footer = styled("footer")`
  display: block;
  background-color: antiquewhite;
`;

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>TETLIS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <h1>TETRIS</h1>
        <Tetris />
      </Main>
      <Footer>
        <a
          href="https://www.cubdesign.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          &copy; cubdesign
        </a>
      </Footer>
    </Container>
  );
};

export default Home;
